spongebob/config/routes.rb
Rails.application.routes.draw do
  root :to => 'spongebob#index'
  resources :users
  get 'register' => 'users#new', :as=>'register'
  get 'logout' => 'user_sessions#destroy', :as=>'logout'
  get 'login' => 'user_sessions#new', :as=>'login'
  resources :user_sessions, :only=>[:create]

  resources :price_details
end

spongebob/app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :name , :message => "Name cannot be blank"
	validates_presence_of :email , :message => "Email cannot be blank"
  validates_uniqueness_of :email , :message => "Email is already registered"
	validates_presence_of :primary_phone , :message => "Mobile Number cannot be blank"
  validates_uniqueness_of :primary_phone , :message => "Mobile Number is already registered"
  acts_as_authentic do |c|
  	c.login_field = :primary_phone
    c.validate_login_field = false
  	c.crypto_provider = Authlogic::CryptoProviders::SCrypt
  end

  scope :active, -> {where("status='active'")}
  scope :allactive, -> {where("status='active' or status='reverify'")}

  before_save :set_roles
  has_many :user_roles, class_name: 'UserRoles'
  has_many :roles,-> {where("user_roles.status='active'")} , :through => :user_roles
  accepts_nested_attributes_for :user_roles

  def set_username
		self.username = self.email
	end

	attr_accessor :roles_changed

	def permissions
    roles.map(&:permissions).flatten(1)
  end

  def grantable_roles
    Role.where(:id=>(self.user_roles.active.where(:grant_option=>true).map(&:role_id)))
  end

  def manager
    User.find_by_id(self.manager_id)
  end

  def roles_ids
    user_roles.active.map(&:role_id)
  end

  def roles_names
    roles.map(&:name)
  end

  def roles
    Role.where(:id=>user_roles.active.map(&:role_id))
  end

  def grantable_roles_ids=(values)
    values||=[]
    values = values.each.map{|h| h.to_i}
    values = values - (values - roles_ids)
    user_roles.each do |ur|
      if values.include?(ur.role_id)
        ur.update_attribute(:grant_option,true)
      else
        ur.update_attribute(:grant_option,false)
      end
    end
  end

  def roles_ids=(values)
    values||=[]
    values = values.each.map{|h| h.to_i}
    assignable_ids = Role.all.map(&:id)
    values= values - (values - assignable_ids)

    old_role_ids= roles_ids

    (old_role_ids-values).each do |role_id|
      ur=self.user_roles.select{|b| b.role_id == role_id}.first
      ur.status='disable'
      ur.grant_option=false
      ur.updated_by = User.current_user.id if User.current_user
      self.roles_changed = true
    end

    values.each do |role_id|
      if(x=self.user_roles.select{|b| b.role_id == role_id}).blank?
        ba=self.user_roles.build(:role_id=>role_id,:status=>'active',:created_by=>User.current_user.id,:grant_option=>false)
        self.roles_changed = true
      else
        x.each do |ur|
          next if ur.status=='active'
          ur.status='active'
          ur.grant_option=false
          ur.updated_by = User.current_user.id if User.current_user
          self.roles_changed = true if ur.changes.any?
        end
      end
    end
  end

  def reset_login_token!
    self.login_token=Authlogic::Random.friendly_token
    self.save
  end

  def set_roles
    self.roles_ids=[] if !['active','reverify'].include?(self.status) || self.manager_id_changed?
  end
end

spongebob/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, :authorize, :only => [:new, :create]
  acl_check :cal_login, :all_actions => :manage
  layout "login"
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_url
    else
      flash[:error] = "Errors : #{@user.errors.full_messages.join(',')}"
      redirect_to :back
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user
    if @user.update_attributes(params[:user])
      flash[:success] = "Account updated!"
      redirect_to :back
    else
      flash[:error] = "Errors : #{@user.errors.full_messages.join(',')}"
      redirect_to :back
    end
  end
end

spongebob/app/views/users/_form.html.erb
<div class="form-group">
	<label for="name" class="control-label">Name</label>
	<%= form.text_field :name,:class=>"form-control", :placeholder=>"e.g John Smith", :autofocus=>true %>
</div>
<div class="form-group">
	<label for="primary_phone" class="control-label">Mobile Number</label>
	<%= form.text_field :primary_phone, :class=>"form-control", :placeholder=>"e.g +91-7042007000" %>
</div>
<div class="form-group">
	<label for="email" class="control-label">Email</label>
	<%= form.text_field :email, :class=>"form-control", :placeholder=>"e.g john@gmail.com" %>
</div>
<div class="form-group">
	<label for="password" class="control-label">Password</label>
	<%= form.password_field :password, :class=>"form-control", :placeholder=>"enter your secret password" %>
</div>
<div class="form-group">
	<label for="password_confirmation" class="control-label">Confirm Password</label>
	<%= form.password_field :password_confirmation, :class=>"form-control", :placeholder=>"retype password" %>
</div>

spongebob/app/views/users/edit.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<%= form_for(@user,:html=>{:class=>'form-signin'}) do |f| %>
			<h2 class="form-signin-heading">Edit Details</h2>
		  <%= render :partial => "form", :object => f %>
		  <%= f.submit "Save", :class=>'btn btn-lg btn-default btn-block' %>
		  <%= link_to "Cancel", user_path %>
		<% end %>
	</div>
</div>

spongebob/app/views/users/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<%= form_for(@user,:html=>{:class=>'form-signin'}) do |f| %>
			<legend class="form-signin-heading">Sign Up</legend>
		  <%= render :partial => "form", :object => f %>
		  <%= f.submit "Save", :class=>'btn btn-lg btn-default btn-block' %>
		  Do you already have account? <a href=<%= login_path %>>Sign In!</a>
		<% end %>
	</div>
</div>

spongebob/app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%=h @user.name %>
</p>
<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>
<p>
  <b>Mobile Number:</b>
  <%=h @user.primary_phone %>
</p>

<%= link_to 'Edit', edit_user_path, :class=>'btn btn-lg btn-default' %>