spongebob/config/routes.rb
Rails.application.routes.draw do
  root :to => 'spongebob#index'
  resources :users
  get 'register' => 'users#new', :as=>'register'
  get 'logout' => 'user_sessions#destroy', :as=>'logout'
  get 'login' => 'user_sessions#new', :as=>'login'
  resources :user_sessions, :only=>[:create]

  resources :price_details
end

spongebob/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

spongebob/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :login_required, :authorize, :only => [:new, :create,:destroy]
  layout "login"
  def new
    if current_user
      flash[:error]="You are already logged in"
      redirect_to root_url
      return
    else
      @user_session = UserSession.new
    end
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:success] = "Welcome back #{@user_session.user.name}!"
      redirect_to root_url
      return
    else
      flash[:error] = "Error : Could not log in! #{@user_session.errors.full_messages.join(',')}"
      redirect_to login_path
      return
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:success] = "You have logged out"
    redirect_to login_path
  end
end

spongebob/app/views/user_sessions/new.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-8">
		<%= form_for(@user_session,:html=>{:class=>'form-signin'}) do |f| %>
			<legend class="form-signin-heading">Please sign in</legend>
		  <%= f.text_field :primary_phone, :class=>"form-control", :placeholder=>"phone number", :autofocus=>true %><br />
		  <%= f.password_field :password, :class=>"form-control", :placeholder=>"password" %>
		  <br />
		  <%= f.submit "Sign In", :class=>'btn btn-lg btn-default btn-block' %>
		  Don't have an account yet? <a href=<%= register_path %>>Sign Up!</a>
		<% end %>
	</div>
</div>