spongebob/config/routes.rb
Rails.application.routes.draw do
  root :to => 'spongebob#index'
  resources :users
  get 'register' => 'users#new', :as=>'register'
  get 'logout' => 'user_sessions#destroy', :as=>'logout'
  get 'login' => 'user_sessions#new', :as=>'login'
  resources :user_sessions, :only=>[:create]

  resources :price_details
end

spongebob/app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= message.html_safe %>
  </div>
<% end %>

spongebob/app/views/shared/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<a class="navbar-brand" href=<%= root_url %>><span><img src='/assets/logo' title="Spongebob" height="25px" width="25px"/>Spongebob</span></a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<% if current_user %>
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/assets/folder_splash" height="25px" width="25px"/> Services <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<%= root_url %>">Request Pickup</a></li>
							<li><a href="<%= root_url %>">Pending Pickups</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Orders</li>
							<li><a href="<%= root_url %>">Track Order</a></li>
							<li><a href="<%= root_url %>">Completed Orders</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/assets/folder_wallet" height="25px" width="25px"/> My Wallet <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<%= root_url %>">Points</a></li>
							<li><a href="<%= root_url %>">Redeem</a></li>
						</ul>
					</li>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle fa fa-rupee" data-toggle="dropdown" role="button" aria-expanded="false" height="25px" width="25px"> Price List <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<%= price_details_path %>">All</li>
							<li><a href="#">Menswear</li>
							<li><a href="#">Womenwear</li>
							<li><a href="#">Partywear</li>
							<li><a href="#">Woolens</li>
							<li><a href="#">Household</li>
							<li><a href="#">Others</li>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/assets/folder_account" height="25px" width="25px"/> <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href=<%= user_path(current_user.id) %>>My Profile</a></li>
							<li><a href=<%= root_url %>>My Addresses</a></li>
							<li><a href=<%= logout_path %>>LogOut</a></li>
						</ul>
					</li>
				</ul>
			<% end %>
		</div><!--/.nav-collapse -->
	</div><!--/.container -->
</nav>